<?php

namespace App\Entity;

use App\App;
use Core\Entity\Entity;
use Core\Config;

/**
 * Class AdminEntity
 *
 * @package App\Entity
 */
class AdminEntity extends Entity
{
    /**
     * @return mixed|null
     */
    public function url()
    {
        return parent::url(); // TODO: Change the autogenerated stub
    }
}