<?php

namespace App\Entity;

use Globals\GlobalEntity;

class UserEntity extends GlobalEntity
{
    public function url()
    {
        return parent::url(); // TODO: Change the autogenerated stub
    }
}