<?php

namespace App\Entity;

use App\App;
use Core\Entity\Entity;
use Core\Config;

class VisiteEntity extends Entity
{
    public function url()
    {
        return parent::url(); // TODO: Change the autogenerated stub
    }
}